[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "typescript"
max-line-length = 100
formatter = {command = 'prettier', args = ["--parser", "typescript"]}
indent = {tab-width = 2, unit = "  "}
auto-format = true
config = { format = {"semicolons" = "remove"}}

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "javascript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true
